version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.3.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
            - node-modules-
      - run: npm i
      - save_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/node:17.3.0
    steps:
      - attach_workspace:
          at: .
      - run: |
          npm run test:coverage
          npm run coverage
      - store_test_results:
          path: .
      - store_artifacts:
          path: ./coverage/lcov-report

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

  test_nightly:
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - build
      - test:
          requires:
            - build
